---

- name:  Second Playbook
  hosts: all
  tasks:

    - name: Only echo
      command: echo "hola a algunos"
    - name: Delete file
      command: sudo rm -rf /root/Playbook-bueno
      become: yes
      become_method: enable
 
